apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: asciiboot
build:
  artifacts:
    - image: asciiboot
      custom:
        buildCommand: |
          ./gradlew bootBuildImage --imageName="$IMAGE"
        dependencies:
          paths:
            - src/main/**
            - build.gradle
            - settings.gradle
  tagPolicy:
    gitCommit: { }
  local:
    push: false
manifests:
  rawYaml:
    - manifests/*.yaml
portForward:
  - resourceType: service
    resourceName: asciiboot-svc
    namespace: asciiboot
    port: 8080
