apiVersion: skaffold/v2beta12
kind: Config
build:
  artifacts:
    - image: springboot-app
      custom:
        buildCommand: ./gradlew bootBuildImage
        dependencies:
          paths:
            - src/main/**
            - build.gradle
            - settings.gradle
  tagPolicy:
    envTemplate:
      template: "0.0.1-SNAPSHOT"
  local:
    push: false
portForward:
  - resourceType: pod
    resourceName: asciiboot
    namespace: default
    port: 8080
deploy:
  kubectl:
    manifests:
      - springboot-*
