apiVersion: skaffold/v2beta12
kind: Config
build:
  artifacts:
    - image: asciiboot-dev
      custom:
        buildCommand: |
          ./gradlew bootBuildImage --imageName="$IMAGE"
        dependencies:
          paths:
            - src/main/**
            - build.gradle
            - settings.gradle
  tagPolicy:
    gitCommit: { }
  local:
    push: false
deploy:
  kubectl:
    manifests:
      - manifests/*.yaml
portForward:
  - resourceType: pod
    resourceName: asciiboot
    namespace: default
    port: 8080
