apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: asciiboot
  name: asciiboot
spec:
  containers:
  - image: springboot-app:0.0.1-SNAPSHOT
    name: asciiboot
    resources: {}
