apiVersion: v1
kind: Pod
metadata:
  labels:
    run: asciiboot
  name: asciiboot
spec:
  containers:
    - image: asciiboot-dev:0.0.1-SNAPSHOT
      name: asciiboot
      readinessProbe:
        httpGet:
          path: /actuator/health/readiness
          port: 8080
