name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        java:
          - 17
          - 19
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Cache .gradle/caches
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-cache-
      - name: Cache .gradle/wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-wrapper-
      - name: Gradle env
        run: ./gradlew -version
      - name: Build
        run: ./gradlew build
      - name: Test
        run: ./gradlew test
      - name: E2E Test
        if: runner.os != 'Windows'
        run: ./scripts/run-e2e.sh
